blank_issues_enabled: false
contact_links:
  - name: ğŸ’™ Processing 4 Issues
    url: https://github.com/processing/processing4/issues
    about: Report issues with Processing 4 here.
  - name: ğŸŒ Processing Website Issues
    url: https://github.com/processing/processing-website/issues
    about: Report issues with the processing.org website here.
  - name: ğŸ’¬ Forum
    url: https://discourse.processing.org/
    about: Have other questions about using Processing? Ask them here!
  - name: ğŸŒ¸ p5.js Issues
    url: https://github.com/processing/p5.js/issues
    about: Report issues with p5.js here.
